//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CaveEditor.rc
//
#define BITMAP_GAME_SHEET               2
#define BUTTON_PROP_ADD                 3
#define DIALOG_NTE_COPYFROM             9
#define ICON_MESSAGEBOX                 10
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CAVEEDITOR_DIALOG           102
#define DIALOG_CAVEEDITOR_DIALOG        102
#define TAB_NPCEDIT_BASE                104
#define IDR_MAINFRAME                   128
#define MENU_MAIN                       129
#define MENU_LIST                       131
#define DIALOG_MAP_EDIT                 132
#define DIALOG_TILE_SELECT              135
#define DIALOG_PALETTE_SELECT           136
#define DIALOG_SCRIPT_EDITOR            137
#define DIALOG_PBM_EDITOR               138
#define MENU_PBM                        139
#define DIALOG_DISPLAY_VIEW             140
#define DIALOG_MAP_PROPERITES           141
#define DIALOG_MAP_INFO                 142
#define ICON_WATER                      143
#define DIALOG_ENTITY_INFO              143
#define ICON_SOLID                      144
#define DIALOG_FLAG_DETAIL              144
#define ICON_SEEN                       145
#define MENU_MAP_EDIT_CONTEXT           145
#define ICON_HIDDEN                     146
#define IDC_CURSOR1                     146
#define CURSOR_NULL                     146
#define CURSOR_PIXEL                    146
#define MENU_PBM1                       146
#define MENU_TILESET                    146
#define COMBO_HURT_SOUND                146
#define CBOX_GROUP_NUM                  146
#define DIALOG_GAME_SETTINGS            147
#define COMBO_DEATH_SOUND               147
#define MENU_MAP_EDIT_CONTEXT1          147
#define MENU_MAP_EDIT                   147
#define CURSOR_FILL                     147
#define DIALOG_TILESET_EDITOR           148
#define COMBO_DEATH_GRAPHIC             148
#define CURSOR_RECT                     148
#define IDR_MENU1                       149
#define CURSOR_REPLACE                  149
#define DIALOG_RESIZE                   150
#define DIALOG_PALETTE_EDITOR           151
#define DIALOG_NPC_TABLE_EDITOR         152
#define DIALOG_OPTIONS                  153
#define DIALOG_TEXT                     154
#define DIALOG_WEAPON_EDITOR            155
#define DIALOG_NPC_EXE_EDITOR           156
#define DIALOG_MAP_REORDER              158
#define DIALOG_PROGRESS_BOX             165
#define DIALOG_MAP_TRANSFER             167
#define DIALOG_EVENT_SELECTOR           169
#define IDD_DIALOG1                     175
#define DIALOG_NETGROUP_INFO            175
#define DIALOG_INPUT_BOX                177
#define TAB_NPCEDIT_PAGE3               178
#define IDD_SCROLLABLE                  183
#define TAB_NPCEDIT_PAGE2               184
#define TAB_NPCEDIT_BASE1               185
#define TAB_NPCEDIT_asd                 185
#define TAB_NPCEDIT_PAGE1               185
#define TAB_NPCEDIT_PAGE4               186
#define DIALOG_CREATE_MOD               188
#define DIALOG_AREA_EDIT                190
#define DIALOG_GAMEEDIT_WEAPONS         199
#define DIALOG_GAMEEDIT_BULLET          204
#define DIALOG_GAMEEDIT_NPC             205
#define TAB_NPCEDIT_PAGE5               206
#define DIALOG_ERROR_WINDOW             208
#define DIALOG_MOD_PACKER               210
#define DIALOG_TITLE_MUSIC_EDIT         213
#define DIALOG_EDIT_TITLE_MUSIC         213
#define DLGITEM_PROPERTY_ENTRY          215
#define DIALOG_ENTITY_PROPERTIES        217
#define TAB_NPCEDIT_PAGE7               218
#define DIALOG_MAP_TAB_MANAGER          224
#define MENU_MAP_TAB                    226
#define IDB_BITMAP1                     229
#define TSCDLG_MESSAGE_BOX              230
#define CSMPGUI_CHECKBOX                232
#define BUTTON_SCRIPT_EDIT              1003
#define BUTTON_NPCTABLE_EDIT            1004
#define BUTTON_EDIT_PBM                 1005
#define BUTTON_GAMEPLAY_EDIT            1005
#define BUTTON_DEBUG                    1007
#define BUTTON_GAME_SETTINGS            1011
#define LIST_MAPS                       1012
#define LIST_TILESETS                   1013
#define LIST_SCRIPTS                    1014
#define BUTTON_TILESET_EDIT             1015
#define BUTTON_MAP_EDIT                 1016
#define BUTTON_MAP_DELETE               1017
#define BUTTON_MAP_ADD                  1018
#define BUTTON_TILESET_ADD              1019
#define BUTTON_TILESET_DELETE           1020
#define BUTTON_TILESET_COPY             1021
#define BUTTON_MAP_COPY                 1022
#define BUTTON_MAP_IMPORT               1022
#define LIST_SPRITES                    1023
#define BUTTON_SPRITES_ADD              1024
#define BUTTON_SPRITES_EDIT             1025
#define BUTTON_SPRITES_COPY             1026
#define BUTTON_SPRITES_DELETE           1027
#define LIST_BACKGROUNDS                1028
#define BUTTON_BACKGROUND_ADD           1029
#define BUTTON_BACKGROUND_EDIT          1030
#define BUTTON_BACKGROUND_COPY          1031
#define BUTTON_BACKGROUND_DELETE        1032
#define STATIC_MAPS                     1033
#define STATIC_TILESET                  1034
#define STATIC_TILESETS                 1034
#define STATIC_SPRITES                  1035
#define STATIC_BACKGROUNDS              1036
#define STATIC_SCRIPTS                  1037
#define LIST_AREAS                      1038
#define BUTTON_AREA_ADD                 1039
#define FRAME_MAP                       1040
#define BUTTON_AREA_COPY                1040
#define BUTTON_AREA_EDIT                1041
#define BUTTON_PROPERTIES               1042
#define BUTTON_AREA_DELETE              1042
#define TEXT_COORDS                     1043
#define STATIC_AREAS                    1043
#define TEXT_COORDS2                    1044
#define TEXT_REDRAW                     1044
#define LIST_MUSIC                      1044
#define BUTTON_MUSIC_ADD                1045
#define BUTTON_MUSIC_PLAY               1046
#define SCROLLBAR_HORZ                  1047
#define BUTTON_MUSIC_EDIT               1047
#define BUTTON_MUSIC_UP                 1047
#define SCROLLBAR_VERT                  1048
#define BUTTON_MUSIC_DELETE             1048
#define STATIC_MUSIC                    1049
#define BUTTON_MUSIC_EDIT2              1050
#define BUTTON_MUSIC_DOWN               1050
#define CHECK_FRONT_TILES               1051
#define CHECK_BACK_TILES                1052
#define CHECK_BACKGROUND                1053
#define CHECK_ENTITIES                  1054
#define CHECK_ENTITY_SPRITES            1055
#define BUTTON_SYNTAX                   1057
#define CHECK_ENTITY_TEXT               1058
#define BUTTON_EDIT_COMMAND             1058
#define BUTTON_SAVE                     1059
#define BUTTON_DETAILS                  1061
#define TEXT_COMMAND                    1062
#define TEXT_SYNTAX                     1063
#define TEXT_DESC                       1064
#define LIST_COMMANDS                   1065
#define TEXT_EXTRAS                     1066
#define BUTTON_SHOWMSGBOX               1066
#define EDIT_SCRIPT                     1067
#define RECT_DISPLAY                    1069
#define EDIT_MAP_NAME                   1070
#define EDIT_MAP_CAPTION                1071
#define COMBO_MAP_TILESET               1072
#define COMBO_MAP_BACKGROUND_SCROLL     1073
#define COMBO_MAP_BACKGROUND            1074
#define COMBO_MAP_NPC_TILESET1          1075
#define COMBO_MAP_NPC_TILESET2          1076
#define COMBO_BOSS_ID                   1077
#define EDIT_MAP_SIZEX                  1078
#define EDIT_MAP_SIZEY                  1079
#define COMBO_AREA                      1080
#define FRAME_SCRIPT_SMALL              1081
#define FRAME_SCRIPT_LARGE              1082
#define CHECK_TILE_GRID                 1082
#define FRAME_SCRIPT_HELP               1082
#define CHECK_TILE_TYPES                1083
#define BUTTON_MAP_SCRIPT               1086
#define FRAME_INFO                      1089
#define RADIO_DRAW_TILES                1090
#define RADIO_FILL_TILES                1091
#define RADIO_BLOCK_TILES               1092
#define RADIO_RECT_TILES                1092
#define RADIO_REPLACE_TILES             1093
#define FRAME_TILE_VIEW                 1094
#define EDIT_ENTITY_ID                  1097
#define EDIT_EVENT_ID                   1098
#define EDIT_FLAG_ID                    1099
#define EDIT_FLAGS                      1100
#define BUTTON_FLAG_DETAILS             1101
#define CHECK_FLAG1                     1102
#define BUTTON_PROPERTY_DETAILS         1102
#define CHECK_FLAG2                     1103
#define CHECK_FLAG3                     1104
#define CHECK_FLAG4                     1105
#define CHECK_FLAG5                     1106
#define CHECK_FLAG6                     1107
#define CHECK_FLAG7                     1108
#define CHECK_FLAG8                     1109
#define CHECK_FLAG9                     1110
#define CHECK_FLAG10                    1111
#define CHECK_FLAG11                    1112
#define CHECK_FLAG12                    1113
#define CHECK_FLAG13                    1114
#define CHECK_FLAG14                    1115
#define CHECK_FLAG15                    1116
#define CHECK_FLAG16                    1117
#define CHECK_FLAG17                    1118
#define CHECK_FLAG18                    1119
#define TEXT_INFO                       1120
#define CHECK_FLAG19                    1120
#define FRAME_ENTITY                    1121
#define IDC_BUTTON1                     1122
#define BUTTON_SHOW_TILESET             1122
#define BUTTON_NEXT                     1122
#define TEXT_SCRDET_BUTTON0             1122
#define BUTTON_MS_OK                    1122
#define BUTTON_ADD_ZONE                 1122
#define BUTTON_WEAPON_LEVEL_1           1122
#define BUTTON_CHANGE_DEFAULT_MOD       1122
#define BUTTON_SELECT_OUT_DIR           1122
#define BUTTON_PROP_DOWN                1122
#define BUTTON_PREV                     1123
#define TEXT_SCRDET_BUTTON1             1123
#define BUTTON_MS_CANCEL                1123
#define BUTTON_REMOVE_ZONE              1123
#define BUTTON_WEAPON_LEVEL_2           1123
#define BUTTON_PROP_UP                  1123
#define BUTTON_OK                       1124
#define TEXT_SCRDET_BUTTON2             1124
#define BUTTON_NAME_ZONE                1124
#define BUTTON_PROP_DELETE              1124
#define TEXT_INDEX                      1125
#define TEXT_RED                        1126
#define EDIT_START_EVENT                1126
#define TEXT_GREEN                      1127
#define EDIT_WIDTH                      1127
#define EDIT_TITLE_EVENT                1127
#define BUTTON_WEAPON_LEVEL_3           1127
#define TEXT_BLUE                       1128
#define EDIT_HEIGHT                     1128
#define EDIT_START_FACING               1128
#define TEXT_HEIGHT                     1129
#define EDIT_START_X                    1129
#define TEXT_WIDTH                      1130
#define EDIT_START_Y                    1130
#define FRAME_TILESET                   1131
#define EDIT_TITLE_X                    1131
#define FRAME_BACKGROUND                1132
#define EDIT_TITLE_Y                    1132
#define EDIT_COLLECTABLE_X              1133
#define EDIT_COLLECTABLE_Y              1134
#define EDIT_HP                         1135
#define EDIT_COLLECTABLE_W              1135
#define EDIT_ATTACK                     1136
#define EDIT_OPTION_1                   1136
#define EDIT_COLLECTABLE_H              1136
#define EDIT_XP                         1137
#define EDIT_OPTION_2                   1137
#define EDIT_AGILITY_INDEX              1137
#define EDIT_NPC_NAME                   1138
#define EDIT_SHORTNAME_1                1138
#define EDIT_SHORTNAME_2                1139
#define EDIT_OPTION_3                   1140
#define COMBO_TILESET                   1141
#define COMBO_TEST_SPRITESHEET_LIST     1142
#define FRAME_NPC                       1144
#define EDIT_HIT_TOP                    1145
#define EDIT_HIT_LEFT                   1146
#define EDIT_HIT_RIGHT                  1147
#define EDIT_HIT_BOTTOM                 1148
#define EDIT_DISPLAY_TOP                1149
#define EDIT_DISPLAY_LEFT               1150
#define EDIT_DISPLAY_RIGHT              1151
#define EDIT_DISPLAY_BOTTOM             1152
#define COMBO_TEST_TILESET              1153
#define BUTTON_CANCEL                   1154
#define EDIT_DESC                       1156
#define EDIT_DESC1                      1157
#define EDIT_DESC2                      1158
#define EDIT_OPTION1                    1159
#define EDIT_OPTION2                    1160
#define CHECK_1                         1161
#define CHECK_2                         1162
#define TEXT_DEBUG                      1162
#define IDC_EDIT1                       1163
#define EDIT_SCALE                      1163
#define EDIT_NAME                       1163
#define EDIT_TEXT                       1163
#define EDIT_PBM_EXT                    1163
#define EDIT_WEP_DAMAGE                 1163
#define EDIT_NPC_CODE                   1163
#define IDC_NPCTOCOPYFROM               1163
#define INPUT_MS_XPOS                   1163
#define INPUT_BOX_INPUT_BOX             1163
#define INPUT_MTITLE                    1163
#define EDIT_WEAPON_NAME                1163
#define EDIT_OUT_PATH                   1163
#define EDIT_NPC_ACT_NAME               1163
#define EDIT_PROP_NAME                  1163
#define EDIT_SCALE2                     1164
#define EDIT_TILESET_SCALE              1164
#define EDIT_WEP_HITS                   1164
#define EDIT_NPC_CODE_RAW               1164
#define INPUT_MS_YPOS                   1164
#define INPUT_MAUTHOR                   1164
#define EDIT_EVENT_EVERYONE_DIED        1164
#define EDIT_NPC_ACT_NO                 1164
#define EDIT_PROP_VALUE                 1164
#define RADIO_WHEEL_ZOOM                1165
#define EDIT_WEP_RANGE                  1165
#define INPUT_MDATAPATH                 1165
#define EDIT_EVENT_DROWN                1165
#define RADIO_WHEEL_SCROLL              1166
#define EDIT_WEP_SHOT_WIDTH             1166
#define EDIT_EVENT_DEATH                1166
#define CHECK_TILESET_WINDOW            1167
#define EDIT_WEP_SHOT_HEIGHT            1167
#define EDIT_WEP_WALL_HEIGHT            1168
#define EDIT_FLAG_CORE_DROWN            1168
#define TEXT_ALPHA                      1169
#define EDIT_WEP_WALL_WIDTH             1169
#define EDIT_EVENT_COREDROWN            1169
#define SLIDER_ALPHA                    1170
#define EDIT_WEP_LEFT_GRPHIC_OFFSET     1170
#define TEXT_ALPHA_TEST_AREA            1171
#define EDIT_WEP_RIGHT_GRPHIC_OFFSET    1171
#define EDIT_WEP_VERT_GRPHIC_OFFSET     1172
#define SLIDER_BLUE                     1173
#define EDIT_WEP_EXP                    1173
#define SLIDER_GREEN                    1174
#define EDIT_WEP_NAME                   1174
#define SLIDER_RED                      1175
#define FRAME_COLOR                     1176
#define TEXT_RED2                       1177
#define TEXT_GREEN2                     1178
#define TEXT_BLUE2                      1179
#define FRAME_24BIT                     1180
#define EDIT_TITLE                      1181
#define EDIT_SAVE_FILE_NAME             1182
#define EDIT_AUTHOR                     1182
#define CHECK_NO_C_PIXEL                1183
#define EDIT_VERSION_1                  1183
#define EDIT_VERSION_2                  1184
#define EDIT_C_PIXEL                    1185
#define EDIT_VERSION_3                  1185
#define EDIT_START_HP                   1186
#define EDIT_START_MAX_HP               1187
#define EDIT_VERSION_4                  1188
#define FRAME_WEP_IMAGE                 1190
#define TEXT_WEP_LEVEL                  1191
#define CHECK_FLAG01                    1193
#define CHECK_FLAG02                    1194
#define TEXT_OPCODE_DESC                1194
#define CHECK_FLAG04                    1195
#define CHECK_FLAG08                    1196
#define TEXT_SCRIPT_DESC                1196
#define TEXT_SCRIPT_COMMAND             1197
#define CHECK_FLAG20                    1198
#define TEXT_SCRIPT_FRAME1              1198
#define CHECK_FLAG40                    1199
#define TEXT_SCRIPT_FRAME2              1199
#define CHECK_FLAG80                    1200
#define TEXT_SCRIPT_DETAILS             1200
#define IDC_LIST2                       1201
#define LIST_EVENTS                     1201
#define COMBO_START_MAP                 1202
#define COMBO_TITLE_MAP                 1203
#define IDC_COMBO1                      1203
#define COMBO_ENTITY_TYPE               1203
#define COMBO_LOBBY_STAGE               1203
#define LIST_WEAPON_TEST_ANIMATIONS     1203
#define CHECK_READ_ONLY                 1204
#define CHECK_COMPILE_ON_SAVE           1205
#define EDIT_COLORDEPTH                 1206
#define BUTTON_COPYFROM                 1207
#define CHECK_ALT_RECT_EDIT_MODE        1207
#define BUTTON_IMPORT_NPC_TBL           1208
#define CHECK_PLAY_SOUND                1208
#define CHECK_FOCUS_WINDOW_ON_MAPLOAD   1209
#define CHECK_ALT_RECT_EDIT_MODE3       1210
#define CHECK_MAXIMIZE_WINDOW_ON_INITIAL_LOAD 1210
#define CHECK_SYNC_ACROSS_TABS          1211
#define IDC_PROGRESS_CURRENT            1212
#define IDC_PROGRESS_OVERALL            1213
#define TEXT_PROGRESS_TASK              1215
#define TEXT_PROGRESS_CURRENT           1216
#define TEXT_PROGRESS_OVERALL           1217
#define BITMAP_MS_MAP_PREVIEW           1217
#define INPUT_MS_EVENT                  1218
#define DROPLIST_MS_MAP                 1220
#define BUTTON_MS_EVENTVIEW             1221
#define BUTTON_EVESEL_ACCEPT            1225
#define BUTTON_EVESEL_BACK              1226
#define RADIO_BRUSH_NETGROUP            1231
#define RADIO_FILL_NETGROUP             1232
#define LIST_ZONE_AREA                  1233
#define BUTTON_INPUTBOX_OK              1235
#define BUTTON_INPUTBOX_CANCEL          1236
#define LABEL_INPUT                     1237
#define LABEL_PLEASE_ENTER              1238
#define NPCEDITOR_TAB                   1244
#define IDC_LIST1                       1247
#define CHECK_DIRTY1                    1248
#define CHECK_DIRTY2                    1249
#define CHECK_DIRTY3                    1250
#define CHECK_DIRTY4                    1251
#define CHECK_DIRTY5                    1252
#define CHECK_DIRTY6                    1253
#define CHECK_DIRTY7                    1254
#define CHECK_DIRTY8                    1255
#define CHECK_DIRTY9                    1256
#define CHECK_DIRTY10                   1257
#define CHECK_DIRTY11                   1258
#define CHECK_DIRTY12                   1259
#define CHECK_DIRTY13                   1260
#define CHECK_DIRTY14                   1261
#define CHECK_DIRTY15                   1262
#define CHECK_DIRTY16                   1263
#define CHECK_DIRTY17                   1264
#define CHECK_DIRTY18                   1265
#define CHECK_DIRTY19                   1266
#define CHECK_DIRTY20                   1267
#define CHECK_DIRTY21                   1268
#define CHECK_DIRTY22                   1269
#define CHECK_DIRTY23                   1270
#define CHECK_DIRTY24                   1271
#define CHECK_DIRTY25                   1272
#define LBL                             1274
#define LBL2                            1275
#define EDIT_AREA_NAME                  1275
#define LBL3                            1276
#define CHECK_SINGLE_PLAYER             1276
#define STATIC_AREA_FLAGS               1277
#define CHECK_KEEP_IN_RELEASE           1278
#define LIST_WEAPONS                    1279
#define BUTTON_WEAPON_DUPLICATE         1280
#define BUTTON_WEAPON_DELETE            1282
#define BUTTON_WEAPON_SAVE              1283
#define PICTURE_ARMS                    1284
#define BUTTON_WEAPON_ADD               1285
#define EDIT_WEAPON_EXP                 1286
#define EDIT_WEAPON_DISP_X              1291
#define BUTTON_WEAPON_LOAD_PLAYER       1293
#define LABEL_PLAYER_PATH               1294
#define EDIT_WEAPON_DISP_Y              1295
#define CHECK_WEAPON_TEST_ALT_DIR       1296
#define EDIT_BULLET_NAME                1297
#define EDIT_WEAPON_DISP_W              1298
#define EDIT_WEAPON_DISP_H              1299
#define PICTURE_WEAPON_PREVIEW          1300
#define BUTTON_WEAPON_UNLOAD_PLAYER     1305
#define EDIT_WEAPON_OFFSET_X            1311
#define EDIT_WEAPON_OFFSET_Y            1312
#define STATIC_BULLET                   1313
#define BUTTON_BULLET_ADD               1314
#define STATIC_BULLET2                  1314
#define EDIT_WEAPON_VIEW_TOP            1315
#define BUTTON_BULLET_DUPLICATE         1315
#define EDIT_WEAPON_VIEW_BOTTOM         1316
#define BUTTON_BULLET_DELETE            1316
#define EDIT_WEAPON_VIEW_LEFT           1317
#define BUTTON_BULLET_SAVE              1317
#define EDIT_WEAPON_VIEW_RIGHT          1318
#define LIST_BULLETS                    1318
#define CHECK_BULLET_FLAG_1             1319
#define CHECK_BULLET_FLAG_2             1320
#define CHECK_BULLET_FLAG_3             1321
#define CHECK_BULLET_FLAG_4             1322
#define CHECK_BULLET_FLAG_5             1323
#define EDIT_BULLET_DISP_X              1324
#define EDIT_BULLET_DISP_Y              1325
#define EDIT_BULLET_DISP_W              1326
#define EDIT_BULLET_DISP_H              1327
#define CHECK_BULLET_COPY_FLAGS         1328
#define PICTURE_BULLET                  1329
#define CHECK_BULLET_COPY_BEHAVIOR      1330
#define CHECK_BULLET_COPY_SPRITE        1331
#define CHECK_BULLET_COPY_BOUNDS        1332
#define CHECK_BULLET_COPY_COLLISION     1333
#define EDIT_NPC_HITBOX_COPY            1333
#define EDIT_NPC_DISPBOX_COPY           1334
#define EDIT_BULLET_DAMAGE              1337
#define EDIT_BULLET_LIFE                1338
#define EDIT_BULLET_LIFE_COUNT          1339
#define EDIT_BULLET_BOUNDS_W            1340
#define EDIT_BULLET_BOUNDS_H            1341
#define EDIT_BULLET_COL_BOX_W           1342
#define EDIT_NPC_HITBOX_T               1342
#define EDIT_BULLET_COL_BOX_H           1343
#define EDIT_NPC_HITBOX_B               1343
#define COMBO_BULLET_LIST               1344
#define EDIT_NPC_DISPBOX_T              1344
#define EDIT_NPC_DISPBOX_B              1345
#define EDIT_NPC_HITBOX_L               1346
#define EDIT_NPC_HITBOX_R               1347
#define EDIT_NPC_DISPBOX_L              1348
#define EDIT_NPC_DISPBOX_R              1349
#define EDIT_NPC_SPRITE_X               1350
#define EDIT_NPC_SPRITE_Y               1351
#define EDIT_NPC_SPRITE_W               1352
#define EDIT_NPC_SPRITE_H               1353
#define LIST_NPCS                       1354
#define BUTTON_NPC_ADD                  1356
#define BUTTON_NPC_DELETE               1357
#define CHECK_FOCUS_X                   1358
#define BUTTON_ACT_ADD                  1358
#define CHECK_FOCUS_Y                   1359
#define BUTTON_ACT_REMOVE               1359
#define EDIT_CATEGORY                   1360
#define EDIT_ERROR_CONTENTS             1361
#define TEXT_ERROR_TEXT                 1362
#define ERROR_PROGRESS                  1363
#define ERROR_CANCEL                    1365
#define ERROR_OK                        1366
#define CHECK_ALLOW_CARRYING            1367
#define CHECK_ALLOW_AGILITY             1368
#define CHECK_ALLOW_FISHING             1369
#define PICTURE_COLLECTABLE             1370
#define CHECK_ALLOW_COLLECTABLES        1371
#define LIST_COLLECTABLE_SURF           1372
#define CHECK_DRAW_HPBAR                1373
#define CHECK_DRAW_HP                   1374
#define CHECK_DRAW_WEAPONS              1375
#define CHECK_DRAW_AMMO                 1376
#define CHECK_DRAW_EXP_BAR              1377
#define CHECK_DRAW_LEVEL                1378
#define TEXT_MOD_NAME                   1379
#define CHECK_INCLUDE_UNCOMPILED_MAPS   1380
#define CHECK_INCLUDE_DEBUG_MOD         1381
#define TEXT_HELP_0                     1382
#define TEXT_HELP_1                     1383
#define BUTTON_PACK_MOD                 1384
#define COMBO_MUSIC_TITLE               1386
#define COMBO_MUSIC_GAMEOVER            1387
#define NPC_EDITOR_ACT_LIST             1387
#define COMBO_MUSIC_NETMENU             1388
#define FRAME_PROP_EDITOR_LIST          1398
#define SCROLL_PROP_EDITOR              1399
#define TAB_MAPS                        1400
#define VERSION_IDENTIFIER_TEXT         1401
#define IDC_MFCSHELLTREE1               1402
#define COMBO_WEAPON_TEMPLATE           1403
#define RADIO_ENTITY                    2000
#define RADIO_MAP                       2001
#define RADIO_NETGROUP                  2002
#define TAB_MAP_SPECIAL                 2003
#define TEXT_SCRDET_INFO0               3000
#define TEXT_SCRDET_INFO1               3001
#define TEXT_SCRDET_INFO2               3002
#define IDC_SCREDT_ARGBOX0              3003
#define IDC_SCREDT_ARGBOX1              3004
#define IDC_SCREDT_ARGBOX2              3005
#define TEXT_SCRDET_TEXT0               3006
#define TEXT_SCRDET_TEXT1               3007
#define TEXT_SCRDET_TEXT2               3008
#define ID_FILE_LOAD                    32772
#define ID_FILE_TEST                    32774
#define ID_HELP_CONTENTS                32775
#define ID_HELP_ABOUT                   32776
#define ID_OPTIONS                      32777
#define ID_EDIT_TILES                   32778
#define ID_EDIT_MAP                     32779
#define ID_EDIT_ENTITYTABLE             32780
#define ID_EDITPROPERTIES               32782
#define ID_COPYMAP                      32783
#define ID_DELETEMAP                    32784
#define ID_EDITMAP                      32786
#define ID_EDITBACKGROUND               32787
#define ID_COPYBACKGROUND               32788
#define ID_DELETEBACKGROUND             32789
#define ID_MAPLIST_                     32790
#define ID_MAPLIST_EDITMAPPROPERTIES    32792
#define ID_MAPLIST_COPYMAP              32793
#define ID_MAPLIST_DELETEMAP            32794
#define ID_BACKGROUNDLIST_EDITBACKGROUND 32795
#define ID_BACKGROUNDLIST_COPYBACKGROUND 32796
#define ID_BACKGROUNDLIST_DELETEBACKGROUND 32797
#define ID_TILESETLIST_EDITTILESET      32798
#define ID_TILESETLIST_COPYTILESET      32799
#define ID_MAPLIST_ADDMAP               32800
#define ID_TILESETLIST_DELETETILESET    32801
#define ID_SPRITESETLIST_EDITSPRITESET  32802
#define ID_SPRITESETLIST_COPYSPRITESET  32803
#define ID_SPRITESETLIST_DELETESPRITESET 32804
#define ID_MAPLIST_EDITMAPSCRIPT        32805
#define ID_SCRIPTLIST                   32806
#define ID_SCRIPTLIST_EDITSCRIPT        32807
#define ID_VIEW_32X32GRID               32812
#define ID_MAPLIST_EDITMAP              32814
#define ID_ENTITY_ADDENTITY             32815
#define ID_ENTITY_DELETEENTITY          32816
#define ID_ENTITY_COPYENTITY            32817
#define ID_ENTITY_PASTEENTITY           32818
#define ID_VIEW_64X64GRID               32820
#define ID_VIEW_16X16GRID               32821
#define ID_VIEW_GRIDOFF                 32822
#define ID_BASE_0                       32823
#define ID_BASE_1                       32824
#define ID_BASE_2                       32825
#define ID_BASE_3                       32826
#define ID_BASE_4                       32827
#define ID_BASE_5                       32828
#define ID_BASE_6                       32829
#define ID_BASE_7                       32830
#define ID_BASE_8                       32831
#define ID_BASE_9                       32832
#define ID_BASE_10                      32833
#define ID_BASE_16                      32834
#define ID_BASE_32                      32835
#define ID_BASE_48                      32836
#define ID_BASE_64                      32837
#define ID_BASE_80                      32838
#define ID_BASE_96                      32839
#define ID_BASE_112                     32840
#define ID_BASE_138                     32841
#define ID_BASE_154                     32842
#define ID_TOOLS_RESIZE                 32845
#define ID_TOOLS_EDITPALETTE            32846
#define ID_FILE_EXIT                    32847
#define ID_MAP_SHIFTMAP                 32848
#define ID_ZOOM_1                       32849
#define ID_ZOOM_1X                      32851
#define ID_ZOOM_2X                      32852
#define ID_ZOOM_3X                      32853
#define ID_ZOOM_4X                      32854
#define ID_ZOOM_05X                     32855
#define ID_MAP_EDITSCRIPT               32856
#define ID_MAP_PROPERTIES               32857
#define ID_MAP_SAVE                     32858
#define ID_COORDS                       32859
#define ID_DATA_EDITBULLETTABLE         32860
#define ID_DATA_WEAPONTABLE             32861
#define ID_DATA_BULLETDATA              32862
#define ID_DATA_WEAPONDATA              32863
#define ID_DATA_NPCEXEDATA              32864
#define ID_DATA_REORDERMAPLIST          32873
#define ID_Menu                         32874
#define ID_MAP_SETSTARTLOCATION         32875
#define ID_ENTITYSELECTED_ID            32876
#define ID_SORTENTITIIESBY_CATEGORY     32882
#define ID_SORTENTITIIESBY_NAME         32883
#define ID_SORTENTITIIESBY_IDNUMBER     32884
#define ID_ENTITIES_DELETEALL           32885
#define ID_FILE_SAVEMAPLIST             32886
#define ASD                             32887
#define ID_DATA_COMPILE_MAPS            32888
#define ID_FILE_EQWER                   32889
#define ID_FILE_NEW_MOD                 32890
#define ID_AREALIST_EDITAREA            32891
#define ID_AREALIST_COPYAREA            32892
#define ID_AREALIST_DELETEAREA          32893
#define ID_FILE_SAVERELEASEMOD          32894
#define ID_FILE_COMPILERELEASEMOD       32895
#define ID_EDITGAMEPLAY_EDITWEAPONS     32896
#define ID_EDITGAMEPLAY_ENFORCEOPTIONS  32897
#define ID_EDITGAMEPLAY_EDITBULLETS     32898
#define ID_EDITGAMEPLAY_EDITNPCS        32899
#define ID_DATA_IMPORTMAPS              32900
#define ID_MUSICLIST_ADDMUSIC           32901
#define ID_MUSICLIST_DELETEMUSIC        32902
#define ID_EDITGAMEPLAY_EDITHUD         32903
#define ID_FILE_PACKMOD                 32904
#define ID_MAPTAB_CLOSETAB              32905
#define ID_MAP_CLOSETAB                 32906
#define ID_Menu32907                    32907
#define ID_MAP_OPENGAMEHERE             32908
#define ID_ENTITYSELECTED_OPENGAMEHERE  32909
#define ID_ENTITYNOTSELECTED_OPENGAMEHERE 32910
#define ID_DATA_IMPORTMUSIC             32911

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        235
#define _APS_NEXT_COMMAND_VALUE         32913
#define _APS_NEXT_CONTROL_VALUE         1404
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
